### PR TITLE
pkg/asset/templates: Name the kubeconfig context

### PR DESCRIPTION
**Pull request by dghubble**
Its useful to give the kubeconfig context a name when managing many k8s clusters with configs along a KUBECONFIG path. Until now, I've manually added a name to be able to switch back and forth (`kubectl config use-context NAME`), so it would be handy if that were done automatically.

### CODE REVIEW

**Comment by aaronlevy** [comment]
Not necessarily opposed to this, but if you're specifying a specific kubeconfig (via env var or otherwise) doesn't it only know about the contexts in that file? So wouldn't adding a context to a single-context file not really change anything?

**Comment by chancez** [comment]
@aaronlevy the env var `KUBECONFIG` actually supports multiple files, separated by `:` so you can have multiple files all with unique context names.

**Comment by dghubble** [comment]
Yep, there is a config file per cluster.

**Comment by aaronlevy** [comment]
lgtm

**Comment by dghubble** [comment]
This is still desired. You want a current context to be added to address the concerns of https://github.com/coreos/bootkube/pull/63?

**Pull request merged**
