### PR TITLE
Bump version to v1.3.4_coreos.0

### PR DESCRIPTION
**Pull request by dghubble**
Probably needs to be bumped in the vagrant examples too

### CODE REVIEW

**Comment by aaronlevy** [comment]
Yeah, would you mind updating this in the hack/ examples? I guess I'm gonna have to switch my self-hosted demos to down-grading the control-plane :)

**Comment by dghubble** [comment]
Updated with find-replace. I have a Linux/libvirt setup so someone else will have to validate.

**Comment by aaronlevy** [comment]
vagrant/virtualbox work on linux....

**Comment by aaronlevy** [comment]
Also, this is missing the generated templates (ci will fail)

**Comment by dghubble** [comment]
Last I checked, not without disabling the kvm module, they don't coexist. Added the generated templates.

**Comment by aaronlevy** [comment]
lgtm

**Pull request merged**
